name: Build JOSS paper and tex

# The point of this action is to create a JOSS paper and tex files
# The tex is stripped of JOSS formatting, so that it can be submitted
# to arxiv (following JOSS policy articulated at: 
# https://github.com/openjournals/joss/issues/132#issuecomment-1231338773),
# i.e. it uses the standard 'article' class, rather than joss template.
# Meanwhile, the paper PDF is still formatted in JOSS style.
# 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: TeX and PDF
        uses: docker://openjournals/paperdraft:latest
        with:
          args: '-k paper/paper.md'
        env:
          GIT_SHA: $GITHUB_SHA
          JOURNAL: joss
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: paper/