name: Ruff

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Ruff
      uses: chartboost/ruff-action@v1
      with:
        # version: "latest"
        src: "./pgmuvi"
        # Pass the --fix argument to automatically resolve fixable linting issues
        args: "check -v --output-format=full --show-fixes --fix"
        # Optional: specify a particular version of Ruff to use
        version: "latest"

    - name: Commit changes
      # Use a separate action to commit the fixed files back to the branch
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Apply Ruff fixes
        # Optional: customize committer and author
        committer_name: GitHub Actions Bot
        committer_email: actions@github.com
        author_name: GitHub Actions Bot
        author_email: actions@github.com
