name: Ruff

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run Ruff
      uses: chartboost/ruff-action@v1
      with:
        # version: "latest"
        src: "./pgmuvi"
        args: "check -v --output-format=full --show-fixes"
